#!/usr/bin/env python3
"""Generate the Appendix tables from cases/*.yaml.

Output goes to out/ in this repository and is committed here.  The book
repository copies these files; the two repositories stay separate.

Every table is written once per language in LANGS: English to `<name>.md`,
Japanese to `<name>_ja.md`, the same convention as README.md / README_ja.md.
Both come from the same case files, so they cannot drift apart.

Two rules the output obeys deliberately:

* No generation timestamp.  A timestamp changes on every run and buries the
  real diff.  The header records the Unbound version and the last commit
  that changed cases/ instead.  HEAD would not do: the commit that adds the
  regenerated tables is itself a new HEAD, so the stamp would never match
  and CI could not check that out/ is up to date.
* No free/paid distinction.  Every case appears in one table.  Where an item
  is published is the book repository's decision and is not encoded here.
"""

import pathlib
import subprocess
import sys

from runner.cases import LANGS, Case, load_cases

ROOT = pathlib.Path(__file__).resolve().parent
OUT = ROOT / "out"

UNBOUND_VERSION = "1.26.0"
UNBOUND_TAG = "release-1.26.0"
UNBOUND_COMMIT = "a45da353"

#: Every fixed string in the output, per language.
MESSAGES = {
    "en": {
        "behaviour_title": (
            "# Appendix: behaviour confirmed from the implementation "
            f"(Unbound {UNBOUND_VERSION})"
        ),
        "behaviour_intro": (
            "The category is a claim about the man page. "
            "A = not described in the man page, "
            "B = described, but the description disagrees with the implementation, "
            "C = the description matches the implementation but the result is "
            "counter-intuitive, undecided = not decided yet."
        ),
        "behaviour_head": (
            "| Category | Section | Behaviour | Evidence (source) | man | Status "
            "| Case |"
        ),
        "diff_title": "# Appendix: differences between versions (category D)",
        "diff_none": "There are no category D cases yet.",
        "diff_head": (
            "| Section | Behaviour | Versions | Evidence (source) | man | Status "
            "| Case |"
        ),
        "summary_title": "# Case summary",
        "by_category": "## By category",
        "category_head": "| Category | Cases |",
        "total": "Total",
        "by_status": "## By status",
        "status_head": "| Status | Cases |",
        "multi_title": "## Behaviours decided by two or more layers",
        "multi_head": "| Section | Behaviour | Layers | Case |",
        "single_title": "## Behaviours decided by a single layer",
        "single_head": "| Behaviour | Layer | Case |",
    },
    "ja": {
        "behaviour_title": (
            f"# 付録: 実装から確認した挙動 (Unbound {UNBOUND_VERSION})"
        ),
        "behaviour_intro": (
            "分類は man についての主張である。A = man に記述なし、"
            "B = 記述があるが実装と食い違う、"
            "C = 記述と実装は一致するが結果が直感に反する、"
            "undecided = 判断保留。"
        ),
        "behaviour_head": "| 分類 | 節 | 挙動 | 根拠 (source) | man | 状態 | ケース |",
        "diff_title": "# 付録: バージョンによる差分 (分類 D)",
        "diff_none": "分類 D のケースは現時点で 0 件。",
        "diff_head": "| 節 | 挙動 | 対象バージョン | 根拠 (source) | man | 状態 | ケース |",
        "summary_title": "# ケース集計",
        "by_category": "## 分類別",
        "category_head": "| 分類 | 件数 |",
        "total": "合計",
        "by_status": "## 状態別",
        "status_head": "| 状態 | 件数 |",
        "multi_title": "## コラム候補（層が 2 つ以上のもの）",
        "multi_head": "| 節 | 挙動 | 層 | ケース |",
        "single_title": "## コラムにしないもの（層が 1 つ）",
        "single_head": "| 挙動 | 層 | ケース |",
    },
}


def cases_commit() -> str:
    """The last commit that touched cases/, or "unknown" outside a checkout."""
    try:
        commit = subprocess.run(
            ["git", "log", "-1", "--format=%h", "--", "cases"],
            cwd=ROOT,
            capture_output=True,
            text=True,
            check=True,
        ).stdout.strip()
    except (subprocess.CalledProcessError, FileNotFoundError):
        return "unknown"
    return commit or "unknown"


def header() -> str:
    return (
        "<!-- generated by gen.py. DO NOT EDIT.\n"
        f"     unbound: {UNBOUND_VERSION} ({UNBOUND_TAG}, {UNBOUND_COMMIT})\n"
        f"     cases: {cases_commit()} -->\n"
    )


def cell(text: str) -> str:
    return text.replace("|", "\\|").replace("\n", " ").strip()


def table_rule(head: str) -> str:
    return "| " + " | ".join("---" for _ in head.strip("|").split("|")) + " |"


def behaviour_table(cases: list[Case], lang: str) -> str:
    m = MESSAGES[lang]
    rows = [c for c in cases if c.category in ("A", "B", "C", "undecided")]
    rows.sort(key=lambda c: (c.category, c.chapter, c.id))
    out = [header(), f"\n{m['behaviour_title']}\n", f"{m['behaviour_intro']}\n"]
    out.append(f"{m['behaviour_head']}\n{table_rule(m['behaviour_head'])}")
    for c in rows:
        out.append(
            f"| {c.category} | {cell(c.chapter)} | {cell(c.title[lang])} | "
            f"{cell(c.source[lang])} | {cell(c.manual[lang])} | {c.status} "
            f"| `{c.id}` |"
        )
    return "\n".join(out) + "\n"


def version_diff_table(cases: list[Case], lang: str) -> str:
    m = MESSAGES[lang]
    rows = [c for c in cases if c.category == "D"]
    rows.sort(key=lambda c: (c.chapter, c.id))
    out = [header(), f"\n{m['diff_title']}\n"]
    if not rows:
        out.append(f"{m['diff_none']}\n")
        return "\n".join(out) + "\n"
    out.append(f"{m['diff_head']}\n{table_rule(m['diff_head'])}")
    for c in rows:
        out.append(
            f"| {cell(c.chapter)} | {cell(c.title[lang])} | "
            f"{', '.join(c.versions)} | {cell(c.source[lang])} | "
            f"{cell(c.manual[lang])} | {c.status} | `{c.id}` |"
        )
    return "\n".join(out) + "\n"


def report(cases: list[Case], lang: str) -> str:
    m = MESSAGES[lang]
    out = [header(), f"\n{m['summary_title']}\n"]
    out.append(f"{m['by_category']}\n")
    out.append(f"{m['category_head']}\n{table_rule(m['category_head'])}")
    for cat in ("A", "B", "C", "D", "undecided"):
        out.append(f"| {cat} | {sum(1 for c in cases if c.category == cat)} |")
    out.append(f"| {m['total']} | {len(cases)} |\n")

    out.append(f"{m['by_status']}\n")
    out.append(f"{m['status_head']}\n{table_rule(m['status_head'])}")
    for st in ("verified", "needs-test", "inconclusive"):
        out.append(f"| {st} | {sum(1 for c in cases if c.status == st)} |")
    out.append("")

    out.append(f"{m['multi_title']}\n")
    out.append(f"{m['multi_head']}\n{table_rule(m['multi_head'])}")
    for c in sorted(
        (c for c in cases if c.is_column_candidate), key=lambda c: (c.chapter, c.id)
    ):
        out.append(
            f"| {cell(c.chapter)} | {cell(c.title[lang])} | "
            f"{cell(' + '.join(c.layers[lang]))} | `{c.id}` |"
        )
    out.append("")
    out.append(f"{m['single_title']}\n")
    out.append(f"{m['single_head']}\n{table_rule(m['single_head'])}")
    for c in sorted(
        (c for c in cases if not c.is_column_candidate), key=lambda c: c.id
    ):
        out.append(f"| {cell(c.title[lang])} | {cell(c.layers[lang][0])} | `{c.id}` |")
    return "\n".join(out) + "\n"


def out_name(stem: str, lang: str) -> str:
    return f"{stem}.md" if lang == "en" else f"{stem}_{lang}.md"


def main() -> int:
    cases = load_cases()
    OUT.mkdir(exist_ok=True)
    for lang in LANGS:
        for stem, render in (
            ("appendix-behavior", behaviour_table),
            ("appendix-version-diff", version_diff_table),
            ("case-summary", report),
        ):
            (OUT / out_name(stem, lang)).write_text(
                render(cases, lang), encoding="utf-8"
            )
    print(f"wrote {len(cases)} cases in {len(LANGS)} languages into {OUT}/")
    return 0


if __name__ == "__main__":
    sys.exit(main())
